# Generated by Django 5.1.6 on 2025-03-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100, verbose_name="Марка")),
                ("model", models.CharField(max_length=100, verbose_name="Модель")),
                ("year", models.IntegerField(verbose_name="Год выпуска")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена ($)"
                    ),
                ),
                ("mileage", models.IntegerField(verbose_name="Пробег (км)")),
                (
                    "body_type",
                    models.CharField(max_length=100, verbose_name="Тип кузова"),
                ),
                ("cylinders", models.IntegerField(verbose_name="Количество цилиндров")),
                (
                    "transmission",
                    models.CharField(max_length=100, verbose_name="Трансмиссия"),
                ),
                (
                    "fuel_type",
                    models.CharField(max_length=100, verbose_name="Тип топлива"),
                ),
                ("color", models.CharField(max_length=50, verbose_name="Цвет")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Местоположение"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "db_table": "cars",
            },
        ),
    ]
