# Generated by Django 5.1.6 on 2025-03-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="cylinders",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Количество цилиндров"
            ),
        ),
    ]
