# Generated by Django 5.1.6 on 2025-03-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_person",
                    models.CharField(max_length=200, verbose_name="Продавец"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                (
                    "product",
                    models.CharField(max_length=200, verbose_name="Название продукта"),
                ),
                ("date", models.DateField(verbose_name="Дата продажи")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма продажи ($)",
                    ),
                ),
                (
                    "boxes_shipped",
                    models.IntegerField(verbose_name="Количество отправленных коробок"),
                ),
            ],
            options={
                "verbose_name": "Продажа шоколада",
                "verbose_name_plural": "Продажи шоколада",
                "db_table": "chocolate_sales",
            },
        ),
    ]
